name: CI
on:
  push:
  pull_request:

env:
  PHP_VERSIONS: '8.0 7.4'

jobs:
  call-worklfow:
    uses: bluepsyduck/github-workflow-refactor/.github/workflows/ci-php-general.yaml@master

  prepare-php-versions:
    name: Prepare PHP Versions
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.set-outputs.outputs.list }}
      first: ${{ steps.set-outputs.outputs.first }}
      validateComposer: ${{ steps.set-outputs.outputs.validateComposer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Format PHP version list
        id: list
        uses: sergeysova/jq-action@v2
        with:
          cmd: "jq -nc '$ARGS.positional' --args ${PHP_VERSIONS[@]}"

      - name: Extract first PHP Version
        id: first
        uses: sergeysova/jq-action@v2
        with:
          cmd: "jq -nc '$ARGS.positional[0]' --args ${PHP_VERSIONS[@]}"

      - name: Set PHP Version Matrix
        id: set-outputs
        run: |
          echo '::set-output name=list::${{ steps.list.outputs.value }}'
          echo '::set-output name=first::${{ steps.first.outputs.value }}'
          echo '::set-output name=hasComposerLock::${{ hashFiles('compsoer.lock') != '' }}'

  unit-tests:
    name: Unit Tests
    needs: prepare-php-versions
    strategy:
      fail-fast: false
      matrix:
        php-version: ${{ fromJSON(needs.prepare-php-versions.outputs.list) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
          echo "::add-matcher::.github/problem-matchers/coverage-check.json"

      - name: Update dependencies
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run phpunit
        run: vendor/bin/phpunit --testsuite unit-test --coverage-clover=coverage.xml

      - name: Check coverage.xml existence
        id: check-coverage-file
        uses: andstor/file-existence-action@v1
        with:
          files: coverage.xml

      - name: Run coverage-check
        if: ${{ always() && steps.check-coverage-file.outputs.files_exists == 'true' }}
        run: vendor/bin/coverage-check coverage.xml 100

      - name: Upload coverage as artifacts
        if: ${{ always() && steps.check-coverage-file.outputs.files_exists == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.php-version }}
          path: coverage.xml

      - name: Upload coverage to Codecov
        if: ${{ always() && steps.check-coverage-file.outputs.files_exists == 'true' }}
        uses: codecov/codecov-action@v1
        with:
          name: coverage-${{ matrix.php-version }}
          file: coverage.xml


  integration-tests:
    name: Integration Tests
    needs: prepare-php-versions
    if: ${{ needs.prepare-php-versions.outputs.hasComposerLock }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ${{ fromJSON(needs.prepare-php-versions.outputs.list) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Update dependencies
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run phpunit
        run: vendor/bin/phpunit --testsuite integration-test
