name: CI
on:
  push:
  pull_request:


jobs:
  call-workflow-ci-php-general:
    name: General
    uses: bluepsyduck/github-workflows/.github/workflows/ci-php-general.yaml@master

  call-workflow-ci-php-tests:
    name: Tests
    uses: bluepsyduck/github-workflows/.github/workflows/ci-php-tests.yaml@master
